sudo: required
language: bash
services:
- docker

install: true

before_script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
- docker pull martinkristien/hyped
- docker run -it martinkristien/hyped cd BeagleBone_black; make -j --silent clean all

notifications:
  slack:
    rooms:
        - hypedunlimited:gEtbY2l7hNP2rwgfelMxr6j1#tech-software-repo
   
   
   