sudo: required
language: bash
services:
- docker

install: true

script:
- docker pull martinkristien/hyped
- docker run -it martinkristien/hyped make -C BeagleBone_black -j --silent clean all

notifications:
  slack:
    rooms:
        - hypedunlimited:gEtbY2l7hNP2rwgfelMxr6j1#tech-software-repo
   
   
   